<a href="https://colab.research.google.com/github/Gavesh99324/Google-Colab-Files/blob/main/Data_Cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import os
os.listdir('/content/drive/MyDrive')

['Getting started.pdf',
 '9035923_2020.pdf',
 '9035923_2020.gdoc',
 'UNI 2.pdf',
 'Document 10_1.jpg',
 'IMG_20210612_171843.jpg',
 'IMG_20210612_175242.jpg',
 '6.jpg',
 '11.jpg',
 '9.jpg',
 '5.jpg',
 '4.jpg',
 '8.jpg',
 '2.jpg',
 '10.jpg',
 '3.jpg',
 '1.jpg',
 '7.jpg',
 '13.jpg',
 '12.jpg',
 'University Application.pdf',
 'IMG_20210612_164057.jpg',
 '990841560V-PP (3).JPG.jpg',
 '990841560V-NICF (3).JPG.jpg',
 '990841560V-NICR (3).JPG.jpg',
 '990841560V-PP (2).JPG.jpg',
 '990841560V-NICF (2).JPG.jpg',
 '990841560V-NICR (2).JPG.jpg',
 '990841560V-PP (1).JPG.jpg',
 '990841560V-NICF (1).JPG.jpg',
 '990841560V-NICR (1).JPG.jpg',
 '990841560V-PP.JPG.jpg',
 '990841560V-NICF.JPG.jpg',
 '990841560V-NICR.JPG.jpg',
 'scan.pdf',
 'Activity 1.docx',
 '20APSE 4876',
 '20APSE 4876.zip',
 'IMG_1784.PNG',
 '20APSE4876.pdf',
 '20APSE4876 , QUIZ 02.pdf',
 'IMG_1859.HEIC',
 'IMG_2506.HEIC',
 'IMG_2507.HEIC',
 '2nd Year Application.pdf',
 'CER',
 'Gavesh Jayasuriya (16).pdf',
 'Gavesh Jayasuriya (15).pdf',
 '20APSE4876_Gavesh.pdf',
 'Gavesh_Jayasuriya (17).pdf',
 'Gavesh_Jayasuriya (16).pdf',
 'Gavesh_Jayasuriya (15).pdf',
 'Gavesh_Jayasuriya (14).pdf',
 'Gavesh_Jayasuriya (13).pdf',
 'Gavesh_Jayasuriya (12).pdf',
 '20250601_155633.heic',
 'Gavesh_Jayasuriya (11).pdf',
 'Gavesh_Jayasuriya (10).pdf',
 'Gavesh_Jayasuriya (9).pdf',
 'Gavesh_Jayasuriya (8).pdf',
 'Gavesh_Jayasuriya (7).pdf',
 'Gavesh_Jayasuriya (6).pdf',
 'Gavesh_Jayasuriya (5).pdf',
 'Gavesh_Jayasuriya (4).pdf',
 'Gavesh_Jayasuriya (3).pdf',
 'Gavesh_Jayasuriya (2).pdf',
 'Gavesh_Jayasuriya (1).pdf',
 'Gavesh_Jayasuriya.pdf',
 'Gavesh Jayasuriya (14).pdf',
 'Gavesh Jayasuriya (13).pdf',
 'Gavesh Jayasuriya (12).pdf',
 'Gavesh Jayasuriya (11).pdf',
 'Gavesh Jayasuriya (10).pdf',
 'kidney-ct-scan-images.zip',
 'Original CV Format.pdf',
 'Gavesh Jayasuriya (9).pdf',
 '20APSE4876',
 'Internship Forms',
 '7th Semester',
 '7th Semester.zip',
 'Gavesh Jayasuriya (8).pdf',
 'Gavesh Jayasuriya (7).pdf',
 'Gavesh Jayasuriya (6).pdf',
 'Gavesh Jayasuriya (5).pdf',
 'Gavesh Jayasuriya (4).pdf',
 'Gavesh Jayasuriya (3).pdf',
 'Gavesh Jayasuriya (2).pdf',
 'Gavesh Jayasuriya (1).pdf',
 'Gavesh Jayasuriya.pdf',
 'Student_Management_Book.pdf',
 'Industrial_Training_Presentation_Template_SE (2).pptx',
 '20APSE4876.pptx',
 'video5824380802.mp4',
 'Colab Notebooks',
 'datamining_pratical1.csv',
 'datamining_pratical2.csv']

In [ ]:
file_path="/content/drive/MyDrive/datamining_pratical1.csv"
df=pd.read_csv(file_path)

In [ ]:
df.head()

,Student_ID,Name,Age,Gender,Department,GPA,Attendance,Projects,Internship,Graduated
0,1,Student_1,24,Male,SE,3.70,76.0,0,No,No
1,2,Student_2,24,Male,DS,3.70,76.0,0,No,No
2,3,Student_3,22,Male,SE,2.90,50.0,3,Yes,No
3,4,Student_4,24,Male,DS,2.19,82.0,2,Yes,No
4,5,Student_5,20,Male,IT,3.14,100.0,5,No,Yes

In [ ]:
df.shape

(50, 10)

In [ ]:
df=df.dropna()

In [ ]:
gender_mapping={'Male': 0, 'Female': 1}
df['Gender']=df['Gender'].map(gender_mapping)

In [ ]:
df=df.rename(columns={'projects':'project'})

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 47 entries, 0 to 49
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Student_ID  47 non-null     int64
 1   Name        47 non-null     object
 2   Age         47 non-null     int64
 3   Gender      47 non-null     int64
 4   Department  47 non-null     object
 5   GPA         47 non-null     float64
 6   Attendance  47 non-null     float64
 7   Projects    47 non-null     int64
 8   Internship  47 non-null     object
 9   Graduated   47 non-null     object
dtypes: float64(2), int64(4), object(4)
memory usage: 4.0+ KB

In [ ]:
file_path="/content/drive/MyDrive/datamining_pratical2.csv"
df=pd.read_csv(file_path)

In [ ]:
df.head()

,Student_ID,Name,Age,Gender,Department,GPA,Attendance,Projects,Internship,Graduated
0,1,Student_1,24,Male,SE,3.70,76.0,0,No,No
1,2,Student_2,24,Male,DS,3.70,76.0,0,No,No
2,3,Student_3,22,Male,SE,2.90,50.0,3,Yes,No
3,4,Student_4,24,Male,DS,2.19,82.0,2,Yes,No
4,5,Student_5,20,Male,IT,3.14,100.0,5,No,Yes

In [ ]:
df.shape

(50, 10)

In [ ]:
df.describe()

       Student_ID       Age        GPA   Attendance  Projects
count    50.00000  50.00000  50.000000    47.000000   50.0000
mean     25.50000  21.34000   3.001600   113.212766    1.9600
std      14.57738   1.89101   0.548495   266.788463    1.5513
min       1.00000  18.00000   2.000000    50.000000    0.0000
25%      13.25000  20.00000   2.542500    60.000000    0.2500
50%      25.50000  21.00000   3.120000    76.000000    2.0000
75%      37.75000  23.00000   3.397500    87.500000    3.0000
max      50.00000  24.00000   3.940000  1900.000000    5.0000

In [ ]:
df.loc[df['Attendance'] > 100, 'Attendance'] = np.nan
df

,Student_ID,Name,Age,Gender,Department,GPA,Attendance,Projects,Internship,Graduated
0,1,Student_1,24,Male,SE,3.70,76.0,0,No,No
1,2,Student_2,24,Male,DS,3.70,76.0,0,No,No
2,3,Student_3,22,Male,SE,2.90,50.0,3,Yes,No
3,4,Student_4,24,Male,DS,2.19,82.0,2,Yes,No
4,5,Student_5,20,Male,IT,3.14,100.0,5,No,Yes
5,6,Student_6,22,Male,SE,3.34,NaN,4,No,Yes
6,7,Student_7,22,Fe,DS,3.33,93.0,2,No,No
7,8,Student_8,24,Female,CS,3.18,73.0,3,No,No
8,9,Student_9,19,Male,IT,2.55,64.0,3,No,Yes
9,10,Student_10,20,Female,DS,3.12,81.0,2,No,Yes
10,11,Student_11,24,Female,CS,2.77,81.0,3,Yes,No
11,12,Student_12,20,Female,DS,3.94,73.0,2,No,Yes
12,13,Student_13,20,Female,CS,3.70,90.0,1,No,No
13,14,Student_14,22,Male,IT,3.44,98.0,2,Yes,Yes
14,15,Student_15,21,Female,SE,3.12,98.0,2,Yes,No
15,16,Student_16,20,Male,CS,2.51,61.0,3,Yes,Yes
16,17,Student_17,23,Female,DS,2.08,88.0,3,Yes,No
17,18,Student_18,22,Female,IT,3.42,51.0,0,No,Yes
18,19,Student_19,19,Fe,CS,2.22,52.0,0,No,Yes
19,20,Student_20,21,Male,DS,2.88,98.0,1,No,No
20,21,Student_21,23,Female,DS,2.40,86.0,0,No,Yes
21,22,Student_22,23,Male,DS,3.79,98.0,2,No,No
22,23,Student_23,19,Female,CS,2.95,66.0,3,No,Yes
23,24,Student_24,21,Male,CS,3.13,98.0,0,Yes,No
24,25,Student_25,22,Female,CS,3.39,51.0,0,No,Yes
25,26,Student_26,18,Male,SE,2.28,51.0,1,Yes,No
26,27,Student_27,21,Male,CS,3.21,77.0,5,Yes,Yes
27,28,Student_28,19,Female,CS,3.67,72.0,1,No,No
28,29,Student_29,23,Male,CS,2.41,86.0,2,Yes,Yes
29,30,Student_30,22,Female,SE,3.89,81.0,3,No,No
30,31,Student_31,21,Female,CS,3.20,58.0,1,Yes,No
31,32,Student_32,18,Female,DS,3.39,50.0,0,No,No
32,33,Student_33,18,Female,CS,3.76,68.0,3,Yes,Yes
33,34,Student_34,20,Female,DS,3.25,51.0,3,No,No
34,35,Student_35,20,Female,DS,2.59,93.0,0,No,Yes
35,36,Student_36,24,Female,DS,2.21,NaN,1,No,No
36,37,Student_37,19,Female,SE,2.91,81.0,0,No,Yes
37,38,Student_38,21,Female,SE,2.44,55.0,5,No,No
38,39,Student_39,21,Female,SE,2.83,81.0,3,Yes,Yes
39,40,Student_40,24,Female,CS,3.77,NaN,4,Yes,Yes
40,41,Student_41,23,Ma,DS,2.65,60.0,4,Yes,No
41,42,Student_42,23,Ma,SE,2.24,66.0,2,No,Yes
42,43,Student_43,24,Female,SE,3.40,87.0,0,Yes,Yes
43,44,Student_44,23,Female,CS,3.60,NaN,0,No,No
44,45,Student_45,20,Female,SE,2.54,54.0,2,No,Yes
45,46,Student_46,21,Female,CS,3.30,83.0,2,Yes,Yes
46,47,Student_47,24,Female,IT,2.00,55.0,2,Yes,Yes
47,48,Student_48,21,Female,SE,2.71,71.0,3,No,No
48,49,Student_49,18,Female,IT,2.61,60.0,5,Yes,Yes
49,50,Student_50,20,Female,CS,2.33,97.0,0,No,No

In [ ]:
df['Attendance'] = df['Attendance'].fillna(df['Attendance'].median())

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Student_ID  50 non-null     int64
 1   Name        50 non-null     object
 2   Age         50 non-null     int64
 3   Gender      50 non-null     object
 4   Department  50 non-null     object
 5   GPA         50 non-null     float64
 6   Attendance  50 non-null     float64
 7   Projects    50 non-null     int64
 8   Internship  50 non-null     object
 9   Graduated   50 non-null     object
dtypes: float64(2), int64(3), object(5)
memory usage: 4.0+ KB

In [ ]:
df['Gender'] = df['Gender'].replace({'Ma': 'Male', 'Fe': 'Female'})
display(df.head())

,Student_ID,Name,Age,Gender,Department,GPA,Attendance,Projects,Internship,Graduated
0,1,Student_1,24,Male,SE,3.70,76.0,0,No,No
1,2,Student_2,24,Male,DS,3.70,76.0,0,No,No
2,3,Student_3,22,Male,SE,2.90,50.0,3,Yes,No
3,4,Student_4,24,Male,DS,2.19,82.0,2,Yes,No
4,5,Student_5,20,Male,IT,3.14,100.0,5,No,Yes

In [ ]:
df['Gender']=df['Gender'].replace({'male': 0, 'ma': 0, 'female': 1, 'fe': 1})

In [ ]:
file_path="/content/drive/MyDrive/datamining_pratical2.csv"
df=pd.read_csv(file_path)

# Standardize 'Ma' to 'Male' and 'Fe' to 'Female', and convert to lowercase for consistent mapping
df['Gender'] = df['Gender'].replace({'Ma': 'Male', 'Fe': 'Female'})
df['Gender'] = df['Gender'].str.lower()

# Map standardized lowercase gender strings to numerical values
gender_mapping = {'male': 0, 'female': 1}
df['Gender'] = df['Gender'].map(gender_mapping)

print("Gender column standardized and encoded.")
display(df.head())
df.info()

Gender column standardized and encoded.

,Student_ID,Name,Age,Gender,Department,GPA,Attendance,Projects,Internship,Graduated
0,1,Student_1,24,0,SE,3.70,76.0,0,No,No
1,2,Student_2,24,0,DS,3.70,76.0,0,No,No
2,3,Student_3,22,0,SE,2.90,50.0,3,Yes,No
3,4,Student_4,24,0,DS,2.19,82.0,2,Yes,No
4,5,Student_5,20,0,IT,3.14,100.0,5,No,Yes

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Student_ID  50 non-null     int64
 1   Name        50 non-null     object
 2   Age         50 non-null     int64
 3   Gender      50 non-null     int64
 4   Department  50 non-null     object
 5   GPA         50 non-null     float64
 6   Attendance  47 non-null     float64
 7   Projects    50 non-null     int64
 8   Internship  50 non-null     object
 9   Graduated   50 non-null     object
dtypes: float64(2), int64(4), object(4)
memory usage: 4.0+ KB

In [ ]:
df

,Student_ID,Name,Age,Gender,Department,GPA,Attendance,Projects,Internship,Graduated
0,1,Student_1,24,0,SE,3.70,76.0,0,No,No
1,2,Student_2,24,0,DS,3.70,76.0,0,No,No
2,3,Student_3,22,0,SE,2.90,50.0,3,Yes,No
3,4,Student_4,24,0,DS,2.19,82.0,2,Yes,No
4,5,Student_5,20,0,IT,3.14,100.0,5,No,Yes
5,6,Student_6,22,0,SE,3.34,1900.0,4,No,Yes
6,7,Student_7,22,1,DS,3.33,93.0,2,No,No
7,8,Student_8,24,1,CS,3.18,73.0,3,No,No
8,9,Student_9,19,0,IT,2.55,64.0,3,No,Yes
9,10,Student_10,20,1,DS,3.12,81.0,2,No,Yes
10,11,Student_11,24,1,CS,2.77,81.0,3,Yes,No
11,12,Student_12,20,1,DS,3.94,73.0,2,No,Yes
12,13,Student_13,20,1,CS,3.70,90.0,1,No,No
13,14,Student_14,22,0,IT,3.44,98.0,2,Yes,Yes
14,15,Student_15,21,1,SE,3.12,98.0,2,Yes,No
15,16,Student_16,20,0,CS,2.51,61.0,3,Yes,Yes
16,17,Student_17,23,1,DS,2.08,88.0,3,Yes,No
17,18,Student_18,22,1,IT,3.42,51.0,0,No,Yes
18,19,Student_19,19,1,CS,2.22,52.0,0,No,Yes
19,20,Student_20,21,0,DS,2.88,98.0,1,No,No
20,21,Student_21,23,1,DS,2.40,86.0,0,No,Yes
21,22,Student_22,23,0,DS,3.79,98.0,2,No,No
22,23,Student_23,19,1,CS,2.95,66.0,3,No,Yes
23,24,Student_24,21,0,CS,3.13,98.0,0,Yes,No
24,25,Student_25,22,1,CS,3.39,51.0,0,No,Yes
25,26,Student_26,18,0,SE,2.28,51.0,1,Yes,No
26,27,Student_27,21,0,CS,3.21,77.0,5,Yes,Yes
27,28,Student_28,19,1,CS,3.67,72.0,1,No,No
28,29,Student_29,23,0,CS,2.41,86.0,2,Yes,Yes
29,30,Student_30,22,1,SE,3.89,81.0,3,No,No
30,31,Student_31,21,1,CS,3.20,58.0,1,Yes,No
31,32,Student_32,18,1,DS,3.39,50.0,0,No,No
32,33,Student_33,18,1,CS,3.76,68.0,3,Yes,Yes
33,34,Student_34,20,1,DS,3.25,51.0,3,No,No
34,35,Student_35,20,1,DS,2.59,93.0,0,No,Yes
35,36,Student_36,24,1,DS,2.21,NaN,1,No,No
36,37,Student_37,19,1,SE,2.91,81.0,0,No,Yes
37,38,Student_38,21,1,SE,2.44,55.0,5,No,No
38,39,Student_39,21,1,SE,2.83,81.0,3,Yes,Yes
39,40,Student_40,24,1,CS,3.77,NaN,4,Yes,Yes
40,41,Student_41,23,0,DS,2.65,60.0,4,Yes,No
41,42,Student_42,23,0,SE,2.24,66.0,2,No,Yes
42,43,Student_43,24,1,SE,3.40,87.0,0,Yes,Yes
43,44,Student_44,23,1,CS,3.60,NaN,0,No,No
44,45,Student_45,20,1,SE,2.54,54.0,2,No,Yes
45,46,Student_46,21,1,CS,3.30,83.0,2,Yes,Yes
46,47,Student_47,24,1,IT,2.00,55.0,2,Yes,Yes
47,48,Student_48,21,1,SE,2.71,71.0,3,No,No
48,49,Student_49,18,1,IT,2.61,60.0,5,Yes,Yes
49,50,Student_50,20,1,CS,2.33,97.0,0,No,No

In [ ]:
df=df.drop_duplicates()

In [ ]:
df

,Student_ID,Name,Age,Gender,Department,GPA,Attendance,Projects,Internship,Graduated
0,1,Student_1,24,0,SE,3.70,76.0,0,No,No
1,2,Student_2,24,0,DS,3.70,76.0,0,No,No
2,3,Student_3,22,0,SE,2.90,50.0,3,Yes,No
3,4,Student_4,24,0,DS,2.19,82.0,2,Yes,No
4,5,Student_5,20,0,IT,3.14,100.0,5,No,Yes
5,6,Student_6,22,0,SE,3.34,1900.0,4,No,Yes
6,7,Student_7,22,1,DS,3.33,93.0,2,No,No
7,8,Student_8,24,1,CS,3.18,73.0,3,No,No
8,9,Student_9,19,0,IT,2.55,64.0,3,No,Yes
9,10,Student_10,20,1,DS,3.12,81.0,2,No,Yes
10,11,Student_11,24,1,CS,2.77,81.0,3,Yes,No
11,12,Student_12,20,1,DS,3.94,73.0,2,No,Yes
12,13,Student_13,20,1,CS,3.70,90.0,1,No,No
13,14,Student_14,22,0,IT,3.44,98.0,2,Yes,Yes
14,15,Student_15,21,1,SE,3.12,98.0,2,Yes,No
15,16,Student_16,20,0,CS,2.51,61.0,3,Yes,Yes
16,17,Student_17,23,1,DS,2.08,88.0,3,Yes,No
17,18,Student_18,22,1,IT,3.42,51.0,0,No,Yes
18,19,Student_19,19,1,CS,2.22,52.0,0,No,Yes
19,20,Student_20,21,0,DS,2.88,98.0,1,No,No
20,21,Student_21,23,1,DS,2.40,86.0,0,No,Yes
21,22,Student_22,23,0,DS,3.79,98.0,2,No,No
22,23,Student_23,19,1,CS,2.95,66.0,3,No,Yes
23,24,Student_24,21,0,CS,3.13,98.0,0,Yes,No
24,25,Student_25,22,1,CS,3.39,51.0,0,No,Yes
25,26,Student_26,18,0,SE,2.28,51.0,1,Yes,No
26,27,Student_27,21,0,CS,3.21,77.0,5,Yes,Yes
27,28,Student_28,19,1,CS,3.67,72.0,1,No,No
28,29,Student_29,23,0,CS,2.41,86.0,2,Yes,Yes
29,30,Student_30,22,1,SE,3.89,81.0,3,No,No
30,31,Student_31,21,1,CS,3.20,58.0,1,Yes,No
31,32,Student_32,18,1,DS,3.39,50.0,0,No,No
32,33,Student_33,18,1,CS,3.76,68.0,3,Yes,Yes
33,34,Student_34,20,1,DS,3.25,51.0,3,No,No
34,35,Student_35,20,1,DS,2.59,93.0,0,No,Yes
35,36,Student_36,24,1,DS,2.21,NaN,1,No,No
36,37,Student_37,19,1,SE,2.91,81.0,0,No,Yes
37,38,Student_38,21,1,SE,2.44,55.0,5,No,No
38,39,Student_39,21,1,SE,2.83,81.0,3,Yes,Yes
39,40,Student_40,24,1,CS,3.77,NaN,4,Yes,Yes
40,41,Student_41,23,0,DS,2.65,60.0,4,Yes,No
41,42,Student_42,23,0,SE,2.24,66.0,2,No,Yes
42,43,Student_43,24,1,SE,3.40,87.0,0,Yes,Yes
43,44,Student_44,23,1,CS,3.60,NaN,0,No,No
44,45,Student_45,20,1,SE,2.54,54.0,2,No,Yes
45,46,Student_46,21,1,CS,3.30,83.0,2,Yes,Yes
46,47,Student_47,24,1,IT,2.00,55.0,2,Yes,Yes
47,48,Student_48,21,1,SE,2.71,71.0,3,No,No
48,49,Student_49,18,1,IT,2.61,60.0,5,Yes,Yes
49,50,Student_50,20,1,CS,2.33,97.0,0,No,No